spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:Sunja123!}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/hh?serverTimezone=Asia/Seoul}
    username: ${MYSQL_USERNAME:root}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  main:
    allow-circular-references: true
auth:
  jwt:
    secret: asdf