spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  main:
    allow-circular-references: true
  profiles:
    include:
      - aws
      - crdentials
auth:
  jwt:
    secret: asdf
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    s3:
      bucket: hh-blog
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SECRETKEY}