spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:sunja123}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/hh?serverTimezone=Asia/Seoul?validationQuery="select 1"}
    username: ${MYSQL_USERNAME:root}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
  main:
    allow-circular-references: true
auth:
  jwt:
    secret: asdf