spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:sunja123}
    url: ${MYSQL_URL:jdbc:mysql://victolee-1.coykhfnnrzfi.ap-northeast-2.rds.amazonaws.com:3306/HH?serverTimezone=Asia/Seoul}
    username: ${MYSQL_USERNAME:root}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  main:
    allow-circular-references: true
  profiles:
    include:
      - aws
      - crdentials
auth:
  jwt:
    secret: asdf
cloud:
  aws:
    s3:
      bucket: hh-blog
    region:
      static: 버킷지역
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SECRETKEY}
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error