spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sunja123
    url: jdbc:mysql://localhost:3306/hh
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  main:
    allow-circular-references: true
  profiles:
    include:
      - aws
      - crdentials
auth:
  jwt:
    secret: asdf
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error